In [19]:
import statsmodels.api as sm
import pandas as pd

In [20]:
weekly_df = pd.read_csv('../data/walmart_weekly_cleaned.csv')

In [21]:
weekly_df

           date  weekly_sales  holiday_flag
0    2010-02-05   49750740.50             0
1    2010-02-12   48336677.63             1
2    2010-02-19   48276993.78             0
3    2010-02-26   43968571.13             0
4    2010-03-05   46871470.30             0
..          ...           ...           ...
138  2012-09-28   43734899.40             0
139  2012-10-05   47566639.31             0
140  2012-10-12   46128514.25             0
141  2012-10-19   45122410.57             0
142  2012-10-26   45544116.29             0

[143 rows x 3 columns]

In [22]:
X =  sm.add_constant(weekly_df[['holiday_flag']])
y = weekly_df['weekly_sales']
model = sm.OLS(y, X).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           weekly_sales   R-squared:                       0.030
Model:                            OLS   Adj. R-squared:                  0.023
Method:                 Least Squares   F-statistic:                     4.334
Date:                Sun, 25 Oct 2026   Prob (F-statistic):             0.0392
Time:                        19:12:33   Log-Likelihood:                -2418.2
No. Observations:                 143   AIC:                             4840.
Df Residuals:                     141   BIC:                             4846.
Df Model:                           1
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         4.686e+07   4.67e+05    100.415      0.000    4.59e+07    4.78e+07
holiday_flag  3.673e+06   1.76e+06      2.082      0.039    1.85e+05    7.16e+06
==============================================================================
Omnibus:                      140.467   Durbin-Watson:                   1.404
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2178.162
Skew:                           3.587   Prob(JB):                         0.00
Kurtosis:                      20.723   Cond. No.                         3.94
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [23]:
df = pd.read_csv('../data/Walmart.csv')
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [24]:
df['Date'] = pd.to_datetime(df['Date'], format="%d-%m-%Y")

df = df.sort_values(by ='Date', ascending=True).reset_index(drop=True)

df.columns = df.columns.str.lower()

df.head()

,store,date,weekly_sales,holiday_flag,temperature,fuel_price,cpi,unemployment
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106
1,10,2010-02-05,2193048.75,0,54.34,2.962,126.442065,9.765
2,37,2010-02-05,536006.73,0,45.97,2.572,209.852966,8.554
3,17,2010-02-05,789036.02,0,23.11,2.666,126.442065,6.548
4,30,2010-02-05,465108.52,0,39.05,2.572,210.752605,8.324

In [25]:
df['store'] = df['store'].apply(pd.to_numeric)
df['weekly_sales'] = df['weekly_sales'].apply(pd.to_numeric)
df['temperature'] = df['temperature'].apply(pd.to_numeric)
df['fuel_price'] = df['fuel_price'].apply(pd.to_numeric)
df['cpi'] = df['cpi'].apply(pd.to_numeric)
df['unemployment'] = df['unemployment'].apply(pd.to_numeric)
df.head()

,store,date,weekly_sales,holiday_flag,temperature,fuel_price,cpi,unemployment
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106
1,10,2010-02-05,2193048.75,0,54.34,2.962,126.442065,9.765
2,37,2010-02-05,536006.73,0,45.97,2.572,209.852966,8.554
3,17,2010-02-05,789036.02,0,23.11,2.666,126.442065,6.548
4,30,2010-02-05,465108.52,0,39.05,2.572,210.752605,8.324

In [27]:
df = df.groupby(['date', 'store']).agg({
    'weekly_sales':'sum',
    'holiday_flag':'max',
    'temperature':'mean',
    'cpi':'mean',
    'unemployment':'mean'
}).reset_index()

df

,date,store,weekly_sales,holiday_flag,temperature,cpi,unemployment
0,2010-02-05,1,1643690.90,0,42.31,211.096358,8.106
1,2010-02-05,2,2136989.46,0,40.19,210.752605,8.324
2,2010-02-05,3,461622.22,0,45.71,214.424881,7.368
3,2010-02-05,4,2135143.87,0,43.76,126.442065,8.623
4,2010-02-05,5,317173.10,0,39.70,211.653972,6.566
...,...,...,...,...,...,...,...
6430,2012-10-26,41,1316542.59,0,41.80,199.219532,6.195
6431,2012-10-26,42,514756.08,0,70.50,131.193097,6.943
6432,2012-10-26,43,587603.55,0,69.17,214.741539,8.839
6433,2012-10-26,44,361067.07,0,46.97,131.193097,5.217
6434,2012-10-26,45,760281.43,0,58.85,192.308899,8.667

In [36]:
df['month'] =df['date'].dt.month
df['quarter'] = df['date'].dt.quarter

month_dummies = pd.get_dummies(df['month'], prefix='month', drop_first=True)

df = pd.concat([df, month_dummies], axis=1)
df

,date,store,weekly_sales,holiday_flag,temperature,cpi,unemployment,month,quarter,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9,month_10,month_11,month_12
0,2010-02-05,1,1643690.90,0,42.31,211.096358,8.106,2,1,True,False,False,False,False,False,False,False,False,False,False
1,2010-02-05,2,2136989.46,0,40.19,210.752605,8.324,2,1,True,False,False,False,False,False,False,False,False,False,False
2,2010-02-05,3,461622.22,0,45.71,214.424881,7.368,2,1,True,False,False,False,False,False,False,False,False,False,False
3,2010-02-05,4,2135143.87,0,43.76,126.442065,8.623,2,1,True,False,False,False,False,False,False,False,False,False,False
4,2010-02-05,5,317173.10,0,39.70,211.653972,6.566,2,1,True,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6430,2012-10-26,41,1316542.59,0,41.80,199.219532,6.195,10,4,False,False,False,False,False,False,False,False,True,False,False
6431,2012-10-26,42,514756.08,0,70.50,131.193097,6.943,10,4,False,False,False,False,False,False,False,False,True,False,False
6432,2012-10-26,43,587603.55,0,69.17,214.741539,8.839,10,4,False,False,False,False,False,False,False,False,True,False,False
6433,2012-10-26,44,361067.07,0,46.97,131.193097,5.217,10,4,False,False,False,False,False,False,False,False,True,False,False
6434,2012-10-26,45,760281.43,0,58.85,192.308899,8.667,10,4,False,False,False,False,False,False,False,False,True,False,False

In [38]:
month_cols = [col for col in df.columns if col.startswith('month_')]

feature_cols = ['holiday_flag', 'temperature', 'cpi', 'unemployment'] + month_cols

X=df[feature_cols]
X= sm.add_constant(X)

y=df['weekly_sales']

model = sm.OLS(y,X).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           weekly_sales   R-squared:                       0.043
Model:                            OLS   Adj. R-squared:                  0.041
Method:                 Least Squares   F-statistic:                     19.44
Date:                Sun, 25 Oct 2026   Prob (F-statistic):           5.79e-52
Time:                        19:40:21   Log-Likelihood:                -94209.
No. Observations:                6435   AIC:                         1.885e+05
Df Residuals:                    6419   BIC:                         1.886e+05
Df Model:                          15
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         1.555e+06   5.79e+04     26.839      0.000    1.44e+06    1.67e+06
holiday_flag  3.181e+04   2.98e+04      1.068      0.286   -2.66e+04    9.02e+04
temperature    220.6705    687.350      0.321      0.748   -1126.765    1568.106
cpi          -1685.7041    197.914     -8.517      0.000   -2073.683   -1297.726
unemployment -4.433e+04   4082.022    -10.859      0.000   -5.23e+04   -3.63e+04
month_2       1.303e+05   3.84e+04      3.397      0.001    5.51e+04    2.05e+05
month_3       9.506e+04   3.79e+04      2.507      0.012    2.07e+04    1.69e+05
month_4       1.051e+05    3.9e+04      2.698      0.007    2.87e+04    1.81e+05
month_5       1.071e+05   4.21e+04      2.544      0.011    2.46e+04     1.9e+05
month_6       1.362e+05   4.51e+04      3.021      0.003    4.78e+04    2.25e+05
month_7       1.016e+05   4.65e+04      2.182      0.029    1.03e+04    1.93e+05
month_8       1.148e+05   4.68e+04      2.453      0.014     2.3e+04    2.07e+05
month_9       5.316e+04   4.47e+04      1.190      0.234   -3.44e+04    1.41e+05
month_10      6.742e+04   4.05e+04      1.663      0.096   -1.21e+04    1.47e+05
month_11      2.223e+05   4.27e+04      5.206      0.000    1.39e+05    3.06e+05
month_12       3.61e+05   3.96e+04      9.122      0.000    2.83e+05    4.39e+05
==============================================================================
Omnibus:                      294.481   Durbin-Watson:                   1.975
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              322.995
Skew:                           0.532   Prob(JB):                     7.29e-71
Kurtosis:                       2.733   Cond. No.                     3.16e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.16e+03. This might indicate that there are
strong multicollinearity or other numerical problems.