In [2]:
import statsmodels.api as sm
import pandas as pd

In [3]:
weekly_df = pd.read_csv('../data/walmart_weekly_cleaned.csv')

In [4]:
weekly_df

           date  weekly_sales  holiday_flag
0    2010-02-05   49750740.50             0
1    2010-02-12   48336677.63             1
2    2010-02-19   48276993.78             0
3    2010-02-26   43968571.13             0
4    2010-03-05   46871470.30             0
..          ...           ...           ...
138  2012-09-28   43734899.40             0
139  2012-10-05   47566639.31             0
140  2012-10-12   46128514.25             0
141  2012-10-19   45122410.57             0
142  2012-10-26   45544116.29             0

[143 rows x 3 columns]

In [5]:
X =  sm.add_constant(weekly_df[['holiday_flag']])
y = weekly_df['weekly_sales']
model = sm.OLS(y, X).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           weekly_sales   R-squared:                       0.030
Model:                            OLS   Adj. R-squared:                  0.023
Method:                 Least Squares   F-statistic:                     4.334
Date:                Sun, 25 Oct 2026   Prob (F-statistic):             0.0392
Time:                        17:16:56   Log-Likelihood:                -2418.2
No. Observations:                 143   AIC:                             4840.
Df Residuals:                     141   BIC:                             4846.
Df Model:                           1
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         4.686e+07   4.67e+05    100.415      0.000    4.59e+07    4.78e+07
holiday_flag  3.673e+06   1.76e+06      2.082      0.039    1.85e+05    7.16e+06
==============================================================================
Omnibus:                      140.467   Durbin-Watson:                   1.404
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2178.162
Skew:                           3.587   Prob(JB):                         0.00
Kurtosis:                      20.723   Cond. No.                         3.94
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
df = pd.read_csv('../data/Walmart.csv')
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [10]:
df['Date'] = pd.to_datetime(df['Date'], format="%d-%m-%Y")

df = df.sort_values(by ='Date', ascending=True).reset_index(drop=True)

df.columns = df.columns.str.lower()

df.head()

,store,date,weekly_sales,holiday_flag,temperature,fuel_price,cpi,unemployment
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106
1,4,2010-02-05,2135143.87,0,43.76,2.598,126.442065,8.623
2,31,2010-02-05,1469252.05,0,39.05,2.572,210.752605,8.324
3,16,2010-02-05,477409.30,0,19.79,2.580,189.381697,7.039
4,11,2010-02-05,1528008.64,0,46.04,2.572,214.424881,7.368

In [11]:
df['store'] = df['store'].apply(pd.to_numeric)
df['weekly_sales'] = df['weekly_sales'].apply(pd.to_numeric)
df['temperature'] = df['temperature'].apply(pd.to_numeric)
df['fuel_price'] = df['fuel_price'].apply(pd.to_numeric)
df['cpi'] = df['cpi'].apply(pd.to_numeric)
df['unemployment'] = df['unemployment'].apply(pd.to_numeric)
df.head()

,store,date,weekly_sales,holiday_flag,temperature,fuel_price,cpi,unemployment
0,1,2010-02-05,1643690.90,0,42.31,2.572,211.096358,8.106
1,4,2010-02-05,2135143.87,0,43.76,2.598,126.442065,8.623
2,31,2010-02-05,1469252.05,0,39.05,2.572,210.752605,8.324
3,16,2010-02-05,477409.30,0,19.79,2.580,189.381697,7.039
4,11,2010-02-05,1528008.64,0,46.04,2.572,214.424881,7.368

In [12]:
print(type(df['cpi']))

<class 'pandas.Series'>

In [13]:
print(type(df['date']))

<class 'pandas.Series'>

In [14]:
df['cpi'].dtype

dtype('float64')

In [15]:
df['date'].dtype

dtype('<M8[us]')